### ISSUE TITLE
Traffic Rules | "Unmanage" button

### ISSUE THREAD

**Issue by JoeWalters** [ArtimusMaximus/NUA#106]
Separate button to "Unmanage", which deletes rule from NUA DB but NOT from UniFi Router

Bad example: 
![image](https://github.com/ArtimusMaximus/NUA/assets/16560430/d3dbf07c-8c66-4e41-914f-81fc29ceccfd)

**Comment by ArtimusMaximus** [comment]
database deletion only, not Unifi
