### ISSUE TITLE
BUG | Clicking device toggle too quickly breaks connection

### ISSUE THREAD

**Issue by JoeWalters** [ArtimusMaximus/NUA#110]
![image](https://github.com/ArtimusMaximus/NUA/assets/16560430/f522883c-4585-4c6d-8f8f-ba997ae15609)

**Comment by ArtimusMaximus** [comment]
https://www.youtube.com/watch?v=-yIsQPp31L0&ab_channel=ByteGrad
Will initially try "stale closure", if not, will do entire page loading spinner to throttle back to back requests

**Comment by JoeWalters** [comment]
@ArtimusMaximus Resolved by adding spinner with timer.
